// flow-typed signature: 82e9cff038d1b76b9159ca00ed6b60c3
// flow-typed version: <<STUB>>/babel-preset-es2015-node_v^6.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015-node/index' {
  declare module.exports: $Exports<'babel-preset-es2015-node'>;
}
declare module 'babel-preset-es2015-node/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-node'>;
}
