// flow-typed signature: 352ed2e2bee0294a359562159e42935b
// flow-typed version: <<STUB>>/babel-plugin-array-includes_v^2.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-array-includes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-array-includes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-array-includes/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-array-includes/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-array-includes/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-array-includes/lib/index'>;
}
declare module 'babel-plugin-array-includes/test/test.js' {
  declare module.exports: $Exports<'babel-plugin-array-includes/test/test'>;
}
