// flow-typed signature: 53bc025c34991101be0febbcccc7a064
// flow-typed version: <<STUB>>/bookbrainz-data_vgit+https://github.com/bookbrainz/bookbrainz-data-js.git/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bookbrainz-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bookbrainz-data' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bookbrainz-data/models/achievementType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/achievementUnlock' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/alias' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/aliasSet' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/annotation' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/area' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/creatorType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/data/creatorData' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/data/editionData' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/data/publicationData' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/data/publisherData' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/data/workData' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/disambiguation' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/editionFormat' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/editionStatus' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/editor' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/editorEntityVisits' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/editorType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/entities/creator' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/entities/edition' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/entities/publication' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/entities/publisher' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/entities/work' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/entity' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/gender' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/headers/creatorHeader' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/headers/editionHeader' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/headers/publicationHeader' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/headers/publisherHeader' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/headers/workHeader' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/identifier' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/identifierSet' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/identifierType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/language' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/languageSet' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/note' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/publicationType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/publisherSet' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/publisherType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/relationship' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/relationshipSet' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/relationshipType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/releaseEvent' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/releaseEventSet' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/revision' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/revisions/creatorRevision' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/revisions/editionRevision' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/revisions/publicationRevision' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/revisions/publisherRevision' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/revisions/workRevision' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/titleType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/titleUnlock' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/models/workType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testAchievementType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testAchievementUnlock' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testAlias' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testAliasSet' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testAnnotation' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testArea' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testCreator' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testDisambiguation' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testEdition' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testEditionRevision' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testEditor' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testEditorEntityVisits' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testEditorType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testEntity' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testGender' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testIdentifier' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testIdentifierSet' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testIdentifierType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testLanguage' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testPublication' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testPublisher' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testRelationship' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testRelationshipSet' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testRelationshipType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testRevision' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testTitleType' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testTitleUnlock' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/test/testWork' {
  declare module.exports: any;
}

declare module 'bookbrainz-data/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bookbrainz-data/index' {
  declare module.exports: $Exports<'bookbrainz-data'>;
}
declare module 'bookbrainz-data/index.js' {
  declare module.exports: $Exports<'bookbrainz-data'>;
}
declare module 'bookbrainz-data/models/achievementType.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/achievementType'>;
}
declare module 'bookbrainz-data/models/achievementUnlock.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/achievementUnlock'>;
}
declare module 'bookbrainz-data/models/alias.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/alias'>;
}
declare module 'bookbrainz-data/models/aliasSet.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/aliasSet'>;
}
declare module 'bookbrainz-data/models/annotation.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/annotation'>;
}
declare module 'bookbrainz-data/models/area.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/area'>;
}
declare module 'bookbrainz-data/models/creatorType.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/creatorType'>;
}
declare module 'bookbrainz-data/models/data/creatorData.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/data/creatorData'>;
}
declare module 'bookbrainz-data/models/data/editionData.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/data/editionData'>;
}
declare module 'bookbrainz-data/models/data/publicationData.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/data/publicationData'>;
}
declare module 'bookbrainz-data/models/data/publisherData.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/data/publisherData'>;
}
declare module 'bookbrainz-data/models/data/workData.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/data/workData'>;
}
declare module 'bookbrainz-data/models/disambiguation.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/disambiguation'>;
}
declare module 'bookbrainz-data/models/editionFormat.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/editionFormat'>;
}
declare module 'bookbrainz-data/models/editionStatus.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/editionStatus'>;
}
declare module 'bookbrainz-data/models/editor.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/editor'>;
}
declare module 'bookbrainz-data/models/editorEntityVisits.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/editorEntityVisits'>;
}
declare module 'bookbrainz-data/models/editorType.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/editorType'>;
}
declare module 'bookbrainz-data/models/entities/creator.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/entities/creator'>;
}
declare module 'bookbrainz-data/models/entities/edition.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/entities/edition'>;
}
declare module 'bookbrainz-data/models/entities/publication.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/entities/publication'>;
}
declare module 'bookbrainz-data/models/entities/publisher.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/entities/publisher'>;
}
declare module 'bookbrainz-data/models/entities/work.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/entities/work'>;
}
declare module 'bookbrainz-data/models/entity.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/entity'>;
}
declare module 'bookbrainz-data/models/gender.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/gender'>;
}
declare module 'bookbrainz-data/models/headers/creatorHeader.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/headers/creatorHeader'>;
}
declare module 'bookbrainz-data/models/headers/editionHeader.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/headers/editionHeader'>;
}
declare module 'bookbrainz-data/models/headers/publicationHeader.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/headers/publicationHeader'>;
}
declare module 'bookbrainz-data/models/headers/publisherHeader.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/headers/publisherHeader'>;
}
declare module 'bookbrainz-data/models/headers/workHeader.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/headers/workHeader'>;
}
declare module 'bookbrainz-data/models/identifier.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/identifier'>;
}
declare module 'bookbrainz-data/models/identifierSet.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/identifierSet'>;
}
declare module 'bookbrainz-data/models/identifierType.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/identifierType'>;
}
declare module 'bookbrainz-data/models/language.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/language'>;
}
declare module 'bookbrainz-data/models/languageSet.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/languageSet'>;
}
declare module 'bookbrainz-data/models/note.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/note'>;
}
declare module 'bookbrainz-data/models/publicationType.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/publicationType'>;
}
declare module 'bookbrainz-data/models/publisherSet.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/publisherSet'>;
}
declare module 'bookbrainz-data/models/publisherType.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/publisherType'>;
}
declare module 'bookbrainz-data/models/relationship.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/relationship'>;
}
declare module 'bookbrainz-data/models/relationshipSet.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/relationshipSet'>;
}
declare module 'bookbrainz-data/models/relationshipType.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/relationshipType'>;
}
declare module 'bookbrainz-data/models/releaseEvent.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/releaseEvent'>;
}
declare module 'bookbrainz-data/models/releaseEventSet.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/releaseEventSet'>;
}
declare module 'bookbrainz-data/models/revision.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/revision'>;
}
declare module 'bookbrainz-data/models/revisions/creatorRevision.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/revisions/creatorRevision'>;
}
declare module 'bookbrainz-data/models/revisions/editionRevision.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/revisions/editionRevision'>;
}
declare module 'bookbrainz-data/models/revisions/publicationRevision.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/revisions/publicationRevision'>;
}
declare module 'bookbrainz-data/models/revisions/publisherRevision.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/revisions/publisherRevision'>;
}
declare module 'bookbrainz-data/models/revisions/workRevision.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/revisions/workRevision'>;
}
declare module 'bookbrainz-data/models/titleType.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/titleType'>;
}
declare module 'bookbrainz-data/models/titleUnlock.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/titleUnlock'>;
}
declare module 'bookbrainz-data/models/workType.js' {
  declare module.exports: $Exports<'bookbrainz-data/models/workType'>;
}
declare module 'bookbrainz-data/test/testAchievementType.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testAchievementType'>;
}
declare module 'bookbrainz-data/test/testAchievementUnlock.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testAchievementUnlock'>;
}
declare module 'bookbrainz-data/test/testAlias.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testAlias'>;
}
declare module 'bookbrainz-data/test/testAliasSet.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testAliasSet'>;
}
declare module 'bookbrainz-data/test/testAnnotation.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testAnnotation'>;
}
declare module 'bookbrainz-data/test/testArea.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testArea'>;
}
declare module 'bookbrainz-data/test/testCreator.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testCreator'>;
}
declare module 'bookbrainz-data/test/testDisambiguation.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testDisambiguation'>;
}
declare module 'bookbrainz-data/test/testEdition.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testEdition'>;
}
declare module 'bookbrainz-data/test/testEditionRevision.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testEditionRevision'>;
}
declare module 'bookbrainz-data/test/testEditor.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testEditor'>;
}
declare module 'bookbrainz-data/test/testEditorEntityVisits.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testEditorEntityVisits'>;
}
declare module 'bookbrainz-data/test/testEditorType.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testEditorType'>;
}
declare module 'bookbrainz-data/test/testEntity.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testEntity'>;
}
declare module 'bookbrainz-data/test/testGender.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testGender'>;
}
declare module 'bookbrainz-data/test/testIdentifier.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testIdentifier'>;
}
declare module 'bookbrainz-data/test/testIdentifierSet.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testIdentifierSet'>;
}
declare module 'bookbrainz-data/test/testIdentifierType.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testIdentifierType'>;
}
declare module 'bookbrainz-data/test/testLanguage.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testLanguage'>;
}
declare module 'bookbrainz-data/test/testPublication.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testPublication'>;
}
declare module 'bookbrainz-data/test/testPublisher.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testPublisher'>;
}
declare module 'bookbrainz-data/test/testRelationship.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testRelationship'>;
}
declare module 'bookbrainz-data/test/testRelationshipSet.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testRelationshipSet'>;
}
declare module 'bookbrainz-data/test/testRelationshipType.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testRelationshipType'>;
}
declare module 'bookbrainz-data/test/testRevision.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testRevision'>;
}
declare module 'bookbrainz-data/test/testTitleType.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testTitleType'>;
}
declare module 'bookbrainz-data/test/testTitleUnlock.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testTitleUnlock'>;
}
declare module 'bookbrainz-data/test/testWork.js' {
  declare module.exports: $Exports<'bookbrainz-data/test/testWork'>;
}
declare module 'bookbrainz-data/util.js' {
  declare module.exports: $Exports<'bookbrainz-data/util'>;
}
