// flow-typed signature: f87536bc76ec75b0f31c889aeeba9191
// flow-typed version: <<STUB>>/catw_v^1.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'catw'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'catw' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'catw/bin/cmd' {
  declare module.exports: any;
}

declare module 'catw/example/watch' {
  declare module.exports: any;
}

declare module 'catw/test/bin/uc' {
  declare module.exports: any;
}

declare module 'catw/test/brfs' {
  declare module.exports: any;
}

declare module 'catw/test/exec' {
  declare module.exports: any;
}

declare module 'catw/test/tr' {
  declare module.exports: any;
}

declare module 'catw/test/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'catw/bin/cmd.js' {
  declare module.exports: $Exports<'catw/bin/cmd'>;
}
declare module 'catw/example/watch.js' {
  declare module.exports: $Exports<'catw/example/watch'>;
}
declare module 'catw/index' {
  declare module.exports: $Exports<'catw'>;
}
declare module 'catw/index.js' {
  declare module.exports: $Exports<'catw'>;
}
declare module 'catw/test/bin/uc.js' {
  declare module.exports: $Exports<'catw/test/bin/uc'>;
}
declare module 'catw/test/brfs.js' {
  declare module.exports: $Exports<'catw/test/brfs'>;
}
declare module 'catw/test/exec.js' {
  declare module.exports: $Exports<'catw/test/exec'>;
}
declare module 'catw/test/tr.js' {
  declare module.exports: $Exports<'catw/test/tr'>;
}
declare module 'catw/test/watch.js' {
  declare module.exports: $Exports<'catw/test/watch'>;
}
