// flow-typed signature: f6494c0d139e5f6224966804017b2ee7
// flow-typed version: <<STUB>>/connect-redis_v^3.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-redis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-redis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connect-redis/bench/redisbench' {
  declare module.exports: any;
}

declare module 'connect-redis/lib/connect-redis' {
  declare module.exports: any;
}

declare module 'connect-redis/test/connect-redis-test' {
  declare module.exports: any;
}

declare module 'connect-redis/test/redis-server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connect-redis/bench/redisbench.js' {
  declare module.exports: $Exports<'connect-redis/bench/redisbench'>;
}
declare module 'connect-redis/index' {
  declare module.exports: $Exports<'connect-redis'>;
}
declare module 'connect-redis/index.js' {
  declare module.exports: $Exports<'connect-redis'>;
}
declare module 'connect-redis/lib/connect-redis.js' {
  declare module.exports: $Exports<'connect-redis/lib/connect-redis'>;
}
declare module 'connect-redis/test/connect-redis-test.js' {
  declare module.exports: $Exports<'connect-redis/test/connect-redis-test'>;
}
declare module 'connect-redis/test/redis-server.js' {
  declare module.exports: $Exports<'connect-redis/test/redis-server'>;
}
