// flow-typed signature: 6ada83ce78fb65b120991612b8e58205
// flow-typed version: <<STUB>>/express-static-cache_v0.0.6/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-static-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-static-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'express-static-cache/index' {
  declare module.exports: $Exports<'express-static-cache'>;
}
declare module 'express-static-cache/index.js' {
  declare module.exports: $Exports<'express-static-cache'>;
}
