// flow-typed signature: 6edb3af4fcee5e88c072df76ef26c1b5
// flow-typed version: <<STUB>>/font-awesome_v^4.6.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome' {
  declare module.exports: any;
}
