// flow-typed signature: 00ee0b45bc220bdf2582eec13469789d
// flow-typed version: <<STUB>>/git-rev_v^0.2.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-rev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-rev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-rev/example/simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-rev/example/simple.js' {
  declare module.exports: $Exports<'git-rev/example/simple'>;
}
declare module 'git-rev/index' {
  declare module.exports: $Exports<'git-rev'>;
}
declare module 'git-rev/index.js' {
  declare module.exports: $Exports<'git-rev'>;
}
