// flow-typed signature: 5c7902c62fa1a03ce754ecdbbc3de85f
// flow-typed version: <<STUB>>/jquery.mousewheel_v^3.1.9/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery.mousewheel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery.mousewheel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery.mousewheel/jquery.mousewheel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery.mousewheel/jquery.mousewheel.js' {
  declare module.exports: $Exports<'jquery.mousewheel/jquery.mousewheel'>;
}
