// flow-typed signature: 693f75f47bfda5756bcc169431fa50c1
// flow-typed version: <<STUB>>/jsdoc_v^3.4.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdoc/cli' {
  declare module.exports: any;
}

declare module 'jsdoc/jsdoc' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/app' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/augment' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/borrow' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/config' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/doclet' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/env' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/fs' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/name' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/opts/argparser' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/opts/args' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/package' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/path' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/plugins' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/readme' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/schema' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/astbuilder' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/astnode' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/filter' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/handlers' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/parser' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/scanner' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/syntax' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/visitor' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/src/walker' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag/dictionary' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag/dictionary/definitions' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag/inline' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag/type' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tag/validator' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/template' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tutorial' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/tutorial/resolver' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/cast' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/doop' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/dumper' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/error' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/logger' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/markdown' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/runtime' {
  declare module.exports: any;
}

declare module 'jsdoc/lib/jsdoc/util/templateHelper' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/commentConvert' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/commentsOnly' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/escapeHtml' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/eventDumper' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/markdown' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/overloadHelper' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/partial' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/railsTemplate' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/shout' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/sourcetag' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/summarize' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/fixtures/markdown' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/fixtures/overloadHelper' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/fixtures/underscore' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/commentConvert' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/escapeHtml' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/markdown' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/overloadHelper' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/railsTemplate' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/shout' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/sourcetag' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/summarize' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/test/specs/underscore' {
  declare module.exports: any;
}

declare module 'jsdoc/plugins/underscore' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/default/publish' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/default/static/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/default/static/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/default/static/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/haruki/publish' {
  declare module.exports: any;
}

declare module 'jsdoc/templates/silent/publish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdoc/cli.js' {
  declare module.exports: $Exports<'jsdoc/cli'>;
}
declare module 'jsdoc/jsdoc.js' {
  declare module.exports: $Exports<'jsdoc/jsdoc'>;
}
declare module 'jsdoc/lib/jsdoc/app.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/app'>;
}
declare module 'jsdoc/lib/jsdoc/augment.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/augment'>;
}
declare module 'jsdoc/lib/jsdoc/borrow.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/borrow'>;
}
declare module 'jsdoc/lib/jsdoc/config.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/config'>;
}
declare module 'jsdoc/lib/jsdoc/doclet.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/doclet'>;
}
declare module 'jsdoc/lib/jsdoc/env.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/env'>;
}
declare module 'jsdoc/lib/jsdoc/fs.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/fs'>;
}
declare module 'jsdoc/lib/jsdoc/name.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/name'>;
}
declare module 'jsdoc/lib/jsdoc/opts/argparser.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/opts/argparser'>;
}
declare module 'jsdoc/lib/jsdoc/opts/args.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/opts/args'>;
}
declare module 'jsdoc/lib/jsdoc/package.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/package'>;
}
declare module 'jsdoc/lib/jsdoc/path.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/path'>;
}
declare module 'jsdoc/lib/jsdoc/plugins.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/plugins'>;
}
declare module 'jsdoc/lib/jsdoc/readme.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/readme'>;
}
declare module 'jsdoc/lib/jsdoc/schema.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/schema'>;
}
declare module 'jsdoc/lib/jsdoc/src/astbuilder.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/astbuilder'>;
}
declare module 'jsdoc/lib/jsdoc/src/astnode.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/astnode'>;
}
declare module 'jsdoc/lib/jsdoc/src/filter.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/filter'>;
}
declare module 'jsdoc/lib/jsdoc/src/handlers.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/handlers'>;
}
declare module 'jsdoc/lib/jsdoc/src/parser.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/parser'>;
}
declare module 'jsdoc/lib/jsdoc/src/scanner.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/scanner'>;
}
declare module 'jsdoc/lib/jsdoc/src/syntax.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/syntax'>;
}
declare module 'jsdoc/lib/jsdoc/src/visitor.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/visitor'>;
}
declare module 'jsdoc/lib/jsdoc/src/walker.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/src/walker'>;
}
declare module 'jsdoc/lib/jsdoc/tag.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag'>;
}
declare module 'jsdoc/lib/jsdoc/tag/dictionary.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag/dictionary'>;
}
declare module 'jsdoc/lib/jsdoc/tag/dictionary/definitions.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag/dictionary/definitions'>;
}
declare module 'jsdoc/lib/jsdoc/tag/inline.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag/inline'>;
}
declare module 'jsdoc/lib/jsdoc/tag/type.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag/type'>;
}
declare module 'jsdoc/lib/jsdoc/tag/validator.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tag/validator'>;
}
declare module 'jsdoc/lib/jsdoc/template.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/template'>;
}
declare module 'jsdoc/lib/jsdoc/tutorial.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tutorial'>;
}
declare module 'jsdoc/lib/jsdoc/tutorial/resolver.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/tutorial/resolver'>;
}
declare module 'jsdoc/lib/jsdoc/util/cast.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/cast'>;
}
declare module 'jsdoc/lib/jsdoc/util/doop.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/doop'>;
}
declare module 'jsdoc/lib/jsdoc/util/dumper.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/dumper'>;
}
declare module 'jsdoc/lib/jsdoc/util/error.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/error'>;
}
declare module 'jsdoc/lib/jsdoc/util/logger.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/logger'>;
}
declare module 'jsdoc/lib/jsdoc/util/markdown.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/markdown'>;
}
declare module 'jsdoc/lib/jsdoc/util/runtime.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/runtime'>;
}
declare module 'jsdoc/lib/jsdoc/util/templateHelper.js' {
  declare module.exports: $Exports<'jsdoc/lib/jsdoc/util/templateHelper'>;
}
declare module 'jsdoc/plugins/commentConvert.js' {
  declare module.exports: $Exports<'jsdoc/plugins/commentConvert'>;
}
declare module 'jsdoc/plugins/commentsOnly.js' {
  declare module.exports: $Exports<'jsdoc/plugins/commentsOnly'>;
}
declare module 'jsdoc/plugins/escapeHtml.js' {
  declare module.exports: $Exports<'jsdoc/plugins/escapeHtml'>;
}
declare module 'jsdoc/plugins/eventDumper.js' {
  declare module.exports: $Exports<'jsdoc/plugins/eventDumper'>;
}
declare module 'jsdoc/plugins/markdown.js' {
  declare module.exports: $Exports<'jsdoc/plugins/markdown'>;
}
declare module 'jsdoc/plugins/overloadHelper.js' {
  declare module.exports: $Exports<'jsdoc/plugins/overloadHelper'>;
}
declare module 'jsdoc/plugins/partial.js' {
  declare module.exports: $Exports<'jsdoc/plugins/partial'>;
}
declare module 'jsdoc/plugins/railsTemplate.js' {
  declare module.exports: $Exports<'jsdoc/plugins/railsTemplate'>;
}
declare module 'jsdoc/plugins/shout.js' {
  declare module.exports: $Exports<'jsdoc/plugins/shout'>;
}
declare module 'jsdoc/plugins/sourcetag.js' {
  declare module.exports: $Exports<'jsdoc/plugins/sourcetag'>;
}
declare module 'jsdoc/plugins/summarize.js' {
  declare module.exports: $Exports<'jsdoc/plugins/summarize'>;
}
declare module 'jsdoc/plugins/test/fixtures/markdown.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/fixtures/markdown'>;
}
declare module 'jsdoc/plugins/test/fixtures/overloadHelper.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/fixtures/overloadHelper'>;
}
declare module 'jsdoc/plugins/test/fixtures/underscore.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/fixtures/underscore'>;
}
declare module 'jsdoc/plugins/test/specs/commentConvert.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/commentConvert'>;
}
declare module 'jsdoc/plugins/test/specs/escapeHtml.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/escapeHtml'>;
}
declare module 'jsdoc/plugins/test/specs/markdown.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/markdown'>;
}
declare module 'jsdoc/plugins/test/specs/overloadHelper.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/overloadHelper'>;
}
declare module 'jsdoc/plugins/test/specs/railsTemplate.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/railsTemplate'>;
}
declare module 'jsdoc/plugins/test/specs/shout.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/shout'>;
}
declare module 'jsdoc/plugins/test/specs/sourcetag.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/sourcetag'>;
}
declare module 'jsdoc/plugins/test/specs/summarize.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/summarize'>;
}
declare module 'jsdoc/plugins/test/specs/underscore.js' {
  declare module.exports: $Exports<'jsdoc/plugins/test/specs/underscore'>;
}
declare module 'jsdoc/plugins/underscore.js' {
  declare module.exports: $Exports<'jsdoc/plugins/underscore'>;
}
declare module 'jsdoc/templates/default/publish.js' {
  declare module.exports: $Exports<'jsdoc/templates/default/publish'>;
}
declare module 'jsdoc/templates/default/static/scripts/linenumber.js' {
  declare module.exports: $Exports<'jsdoc/templates/default/static/scripts/linenumber'>;
}
declare module 'jsdoc/templates/default/static/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jsdoc/templates/default/static/scripts/prettify/lang-css'>;
}
declare module 'jsdoc/templates/default/static/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jsdoc/templates/default/static/scripts/prettify/prettify'>;
}
declare module 'jsdoc/templates/haruki/publish.js' {
  declare module.exports: $Exports<'jsdoc/templates/haruki/publish'>;
}
declare module 'jsdoc/templates/silent/publish.js' {
  declare module.exports: $Exports<'jsdoc/templates/silent/publish'>;
}
