// flow-typed signature: a795f9562bed654578141ca30b1ddc53
// flow-typed version: <<STUB>>/lodash.compact_v^3.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.compact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.compact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.compact/index' {
  declare module.exports: $Exports<'lodash.compact'>;
}
declare module 'lodash.compact/index.js' {
  declare module.exports: $Exports<'lodash.compact'>;
}
