// flow-typed signature: 62bb2113556f15fba66b322b8beb67db
// flow-typed version: <<STUB>>/passport-musicbrainz-oauth2_vgit+https://github.com/LordSputnik/passport-musicbrainz-oauth2.git/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-musicbrainz-oauth2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-musicbrainz-oauth2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-musicbrainz-oauth2/lib/passport-musicbrainz-oauth2/index' {
  declare module.exports: any;
}

declare module 'passport-musicbrainz-oauth2/lib/passport-musicbrainz-oauth2/strategy' {
  declare module.exports: any;
}

declare module 'passport-musicbrainz-oauth2/test/testStrategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-musicbrainz-oauth2/lib/passport-musicbrainz-oauth2/index.js' {
  declare module.exports: $Exports<'passport-musicbrainz-oauth2/lib/passport-musicbrainz-oauth2/index'>;
}
declare module 'passport-musicbrainz-oauth2/lib/passport-musicbrainz-oauth2/strategy.js' {
  declare module.exports: $Exports<'passport-musicbrainz-oauth2/lib/passport-musicbrainz-oauth2/strategy'>;
}
declare module 'passport-musicbrainz-oauth2/test/testStrategy.js' {
  declare module.exports: $Exports<'passport-musicbrainz-oauth2/test/testStrategy'>;
}
