// flow-typed signature: 51c7fadd277c23179b102a539d1fe4dc
// flow-typed version: <<STUB>>/react-bootstrap_v^0.28.5/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap/dist/react-bootstrap' {
  declare module.exports: any;
}

declare module 'react-bootstrap/dist/react-bootstrap.min' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Accordion' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Alert' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Badge' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Button' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ButtonInput' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Carousel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CarouselCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CarouselItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Clearfix' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Col' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Collapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CollapsibleNav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/deprecated/Navbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Dropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/DropdownButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/DropdownToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Fade' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormControls/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormControls/Static' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Glyphicon' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Grid' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Image' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Input' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/InputBase' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Interpolate' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Jumbotron' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Label' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ListGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ListGroupItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Media' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaHeading' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaLeft' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaList' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaListItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaRight' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MenuItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Modal' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalDialog' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalFooter' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalTitle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Nav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Navbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarBrand' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarCollapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavBrand' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavDropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Overlay' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/PageHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/PageItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Pager' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Pagination' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/PaginationButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Panel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/PanelGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Popover' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ResponsiveEmbed' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Row' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/SafeAnchor' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/SplitButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/SplitToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/styleMaps' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Tab' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Table' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Tabs' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Thumbnail' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Tooltip' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/bootstrapUtils' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/childrenToArray' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/childrenValueInputValidation' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/createChainedFunction' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/createSelectedEvent' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/CustomPropTypes' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/deprecationWarning' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/domUtils' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/EventListener' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/overlayPositionUtils' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/TransitionEvents' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/ValidComponentChildren' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Well' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap/dist/react-bootstrap.js' {
  declare module.exports: $Exports<'react-bootstrap/dist/react-bootstrap'>;
}
declare module 'react-bootstrap/dist/react-bootstrap.min.js' {
  declare module.exports: $Exports<'react-bootstrap/dist/react-bootstrap.min'>;
}
declare module 'react-bootstrap/lib/Accordion.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Accordion'>;
}
declare module 'react-bootstrap/lib/Alert.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Alert'>;
}
declare module 'react-bootstrap/lib/Badge.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Badge'>;
}
declare module 'react-bootstrap/lib/Breadcrumb.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Breadcrumb'>;
}
declare module 'react-bootstrap/lib/BreadcrumbItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/BreadcrumbItem'>;
}
declare module 'react-bootstrap/lib/Button.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Button'>;
}
declare module 'react-bootstrap/lib/ButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ButtonGroup'>;
}
declare module 'react-bootstrap/lib/ButtonInput.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ButtonInput'>;
}
declare module 'react-bootstrap/lib/ButtonToolbar.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ButtonToolbar'>;
}
declare module 'react-bootstrap/lib/Carousel.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Carousel'>;
}
declare module 'react-bootstrap/lib/CarouselCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CarouselCaption'>;
}
declare module 'react-bootstrap/lib/CarouselItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CarouselItem'>;
}
declare module 'react-bootstrap/lib/Clearfix.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Clearfix'>;
}
declare module 'react-bootstrap/lib/Col.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Col'>;
}
declare module 'react-bootstrap/lib/Collapse.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Collapse'>;
}
declare module 'react-bootstrap/lib/CollapsibleNav.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CollapsibleNav'>;
}
declare module 'react-bootstrap/lib/deprecated/Navbar.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/deprecated/Navbar'>;
}
declare module 'react-bootstrap/lib/Dropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Dropdown'>;
}
declare module 'react-bootstrap/lib/DropdownButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/DropdownButton'>;
}
declare module 'react-bootstrap/lib/DropdownMenu.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/DropdownMenu'>;
}
declare module 'react-bootstrap/lib/DropdownToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/DropdownToggle'>;
}
declare module 'react-bootstrap/lib/Fade.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Fade'>;
}
declare module 'react-bootstrap/lib/FormControls/index.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormControls/index'>;
}
declare module 'react-bootstrap/lib/FormControls/Static.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormControls/Static'>;
}
declare module 'react-bootstrap/lib/FormGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormGroup'>;
}
declare module 'react-bootstrap/lib/Glyphicon.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Glyphicon'>;
}
declare module 'react-bootstrap/lib/Grid.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Grid'>;
}
declare module 'react-bootstrap/lib/Image.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Image'>;
}
declare module 'react-bootstrap/lib/index.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/index'>;
}
declare module 'react-bootstrap/lib/Input.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Input'>;
}
declare module 'react-bootstrap/lib/InputBase.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/InputBase'>;
}
declare module 'react-bootstrap/lib/Interpolate.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Interpolate'>;
}
declare module 'react-bootstrap/lib/Jumbotron.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Jumbotron'>;
}
declare module 'react-bootstrap/lib/Label.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Label'>;
}
declare module 'react-bootstrap/lib/ListGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ListGroup'>;
}
declare module 'react-bootstrap/lib/ListGroupItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ListGroupItem'>;
}
declare module 'react-bootstrap/lib/Media.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Media'>;
}
declare module 'react-bootstrap/lib/MediaBody.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaBody'>;
}
declare module 'react-bootstrap/lib/MediaHeading.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaHeading'>;
}
declare module 'react-bootstrap/lib/MediaLeft.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaLeft'>;
}
declare module 'react-bootstrap/lib/MediaList.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaList'>;
}
declare module 'react-bootstrap/lib/MediaListItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaListItem'>;
}
declare module 'react-bootstrap/lib/MediaRight.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaRight'>;
}
declare module 'react-bootstrap/lib/MenuItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MenuItem'>;
}
declare module 'react-bootstrap/lib/Modal.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Modal'>;
}
declare module 'react-bootstrap/lib/ModalBody.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalBody'>;
}
declare module 'react-bootstrap/lib/ModalDialog.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalDialog'>;
}
declare module 'react-bootstrap/lib/ModalFooter.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalFooter'>;
}
declare module 'react-bootstrap/lib/ModalHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalHeader'>;
}
declare module 'react-bootstrap/lib/ModalTitle.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalTitle'>;
}
declare module 'react-bootstrap/lib/Nav.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Nav'>;
}
declare module 'react-bootstrap/lib/Navbar.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Navbar'>;
}
declare module 'react-bootstrap/lib/NavbarBrand.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarBrand'>;
}
declare module 'react-bootstrap/lib/NavbarCollapse.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarCollapse'>;
}
declare module 'react-bootstrap/lib/NavbarHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarHeader'>;
}
declare module 'react-bootstrap/lib/NavbarToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarToggle'>;
}
declare module 'react-bootstrap/lib/NavBrand.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavBrand'>;
}
declare module 'react-bootstrap/lib/NavDropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavDropdown'>;
}
declare module 'react-bootstrap/lib/NavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavItem'>;
}
declare module 'react-bootstrap/lib/Overlay.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Overlay'>;
}
declare module 'react-bootstrap/lib/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/OverlayTrigger'>;
}
declare module 'react-bootstrap/lib/PageHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/PageHeader'>;
}
declare module 'react-bootstrap/lib/PageItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/PageItem'>;
}
declare module 'react-bootstrap/lib/Pager.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Pager'>;
}
declare module 'react-bootstrap/lib/Pagination.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Pagination'>;
}
declare module 'react-bootstrap/lib/PaginationButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/PaginationButton'>;
}
declare module 'react-bootstrap/lib/Panel.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Panel'>;
}
declare module 'react-bootstrap/lib/PanelGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/PanelGroup'>;
}
declare module 'react-bootstrap/lib/Popover.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Popover'>;
}
declare module 'react-bootstrap/lib/ProgressBar.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ProgressBar'>;
}
declare module 'react-bootstrap/lib/ResponsiveEmbed.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ResponsiveEmbed'>;
}
declare module 'react-bootstrap/lib/Row.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Row'>;
}
declare module 'react-bootstrap/lib/SafeAnchor.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/SafeAnchor'>;
}
declare module 'react-bootstrap/lib/SplitButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/SplitButton'>;
}
declare module 'react-bootstrap/lib/SplitToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/SplitToggle'>;
}
declare module 'react-bootstrap/lib/styleMaps.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/styleMaps'>;
}
declare module 'react-bootstrap/lib/Tab.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Tab'>;
}
declare module 'react-bootstrap/lib/Table.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Table'>;
}
declare module 'react-bootstrap/lib/Tabs.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Tabs'>;
}
declare module 'react-bootstrap/lib/Thumbnail.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Thumbnail'>;
}
declare module 'react-bootstrap/lib/Tooltip.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Tooltip'>;
}
declare module 'react-bootstrap/lib/utils/bootstrapUtils.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/bootstrapUtils'>;
}
declare module 'react-bootstrap/lib/utils/childrenToArray.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/childrenToArray'>;
}
declare module 'react-bootstrap/lib/utils/childrenValueInputValidation.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/childrenValueInputValidation'>;
}
declare module 'react-bootstrap/lib/utils/createChainedFunction.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/createChainedFunction'>;
}
declare module 'react-bootstrap/lib/utils/createSelectedEvent.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/createSelectedEvent'>;
}
declare module 'react-bootstrap/lib/utils/CustomPropTypes.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/CustomPropTypes'>;
}
declare module 'react-bootstrap/lib/utils/deprecationWarning.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/deprecationWarning'>;
}
declare module 'react-bootstrap/lib/utils/domUtils.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/domUtils'>;
}
declare module 'react-bootstrap/lib/utils/EventListener.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/EventListener'>;
}
declare module 'react-bootstrap/lib/utils/index.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/index'>;
}
declare module 'react-bootstrap/lib/utils/overlayPositionUtils.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/overlayPositionUtils'>;
}
declare module 'react-bootstrap/lib/utils/TransitionEvents.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/TransitionEvents'>;
}
declare module 'react-bootstrap/lib/utils/ValidComponentChildren.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/ValidComponentChildren'>;
}
declare module 'react-bootstrap/lib/Well.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Well'>;
}
