// flow-typed signature: a3eb247506e7e325d246e71b2e1d4499
// flow-typed version: <<STUB>>/react-sticky_v^5.0.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sticky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sticky' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sticky/lib/channel' {
  declare module.exports: any;
}

declare module 'react-sticky/lib/container' {
  declare module.exports: any;
}

declare module 'react-sticky/lib/index' {
  declare module.exports: any;
}

declare module 'react-sticky/lib/sticky' {
  declare module.exports: any;
}

declare module 'react-sticky/test/setup' {
  declare module.exports: any;
}

declare module 'react-sticky/test/unit/channel' {
  declare module.exports: any;
}

declare module 'react-sticky/test/unit/container' {
  declare module.exports: any;
}

declare module 'react-sticky/test/unit/sticky' {
  declare module.exports: any;
}

declare module 'react-sticky/test/utils' {
  declare module.exports: any;
}

declare module 'react-sticky/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sticky/lib/channel.js' {
  declare module.exports: $Exports<'react-sticky/lib/channel'>;
}
declare module 'react-sticky/lib/container.js' {
  declare module.exports: $Exports<'react-sticky/lib/container'>;
}
declare module 'react-sticky/lib/index.js' {
  declare module.exports: $Exports<'react-sticky/lib/index'>;
}
declare module 'react-sticky/lib/sticky.js' {
  declare module.exports: $Exports<'react-sticky/lib/sticky'>;
}
declare module 'react-sticky/test/setup.js' {
  declare module.exports: $Exports<'react-sticky/test/setup'>;
}
declare module 'react-sticky/test/unit/channel.js' {
  declare module.exports: $Exports<'react-sticky/test/unit/channel'>;
}
declare module 'react-sticky/test/unit/container.js' {
  declare module.exports: $Exports<'react-sticky/test/unit/container'>;
}
declare module 'react-sticky/test/unit/sticky.js' {
  declare module.exports: $Exports<'react-sticky/test/unit/sticky'>;
}
declare module 'react-sticky/test/utils.js' {
  declare module.exports: $Exports<'react-sticky/test/utils'>;
}
declare module 'react-sticky/webpack.config.js' {
  declare module.exports: $Exports<'react-sticky/webpack.config'>;
}
