// flow-typed signature: 82c65697dee19b263a91a0e2446de2f9
// flow-typed version: <<STUB>>/react-fontawesome_v^0.3.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fontawesome' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fontawesome/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fontawesome/lib/index.js' {
  declare module.exports: $Exports<'react-fontawesome/lib/index'>;
}
