// flow-typed signature: 80dc3a013d8ec433be245c7fa40df7ca
// flow-typed version: <<STUB>>/rewire_vv2.5.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rewire'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rewire' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rewire/lib/__get__' {
  declare module.exports: any;
}

declare module 'rewire/lib/__set__' {
  declare module.exports: any;
}

declare module 'rewire/lib/__with__' {
  declare module.exports: any;
}

declare module 'rewire/lib/detectStrictMode' {
  declare module.exports: any;
}

declare module 'rewire/lib/getDefinePropertySrc' {
  declare module.exports: any;
}

declare module 'rewire/lib/getImportGlobalsSrc' {
  declare module.exports: any;
}

declare module 'rewire/lib/index' {
  declare module.exports: any;
}

declare module 'rewire/lib/moduleEnv' {
  declare module.exports: any;
}

declare module 'rewire/lib/rewire' {
  declare module.exports: any;
}

declare module 'rewire/testLib/boolean' {
  declare module.exports: any;
}

declare module 'rewire/testLib/debuggerModule' {
  declare module.exports: any;
}

declare module 'rewire/testLib/emptyModule' {
  declare module.exports: any;
}

declare module 'rewire/testLib/implicitGlobal' {
  declare module.exports: any;
}

declare module 'rewire/testLib/moduleA' {
  declare module.exports: any;
}

declare module 'rewire/testLib/moduleB' {
  declare module.exports: any;
}

declare module 'rewire/testLib/null' {
  declare module.exports: any;
}

declare module 'rewire/testLib/sealedObject' {
  declare module.exports: any;
}

declare module 'rewire/testLib/sharedTestCases' {
  declare module.exports: any;
}

declare module 'rewire/testLib/someOtherModule' {
  declare module.exports: any;
}

declare module 'rewire/testLib/strictModule' {
  declare module.exports: any;
}

declare module 'rewire/testLib/throwError' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rewire/lib/__get__.js' {
  declare module.exports: $Exports<'rewire/lib/__get__'>;
}
declare module 'rewire/lib/__set__.js' {
  declare module.exports: $Exports<'rewire/lib/__set__'>;
}
declare module 'rewire/lib/__with__.js' {
  declare module.exports: $Exports<'rewire/lib/__with__'>;
}
declare module 'rewire/lib/detectStrictMode.js' {
  declare module.exports: $Exports<'rewire/lib/detectStrictMode'>;
}
declare module 'rewire/lib/getDefinePropertySrc.js' {
  declare module.exports: $Exports<'rewire/lib/getDefinePropertySrc'>;
}
declare module 'rewire/lib/getImportGlobalsSrc.js' {
  declare module.exports: $Exports<'rewire/lib/getImportGlobalsSrc'>;
}
declare module 'rewire/lib/index.js' {
  declare module.exports: $Exports<'rewire/lib/index'>;
}
declare module 'rewire/lib/moduleEnv.js' {
  declare module.exports: $Exports<'rewire/lib/moduleEnv'>;
}
declare module 'rewire/lib/rewire.js' {
  declare module.exports: $Exports<'rewire/lib/rewire'>;
}
declare module 'rewire/testLib/boolean.js' {
  declare module.exports: $Exports<'rewire/testLib/boolean'>;
}
declare module 'rewire/testLib/debuggerModule.js' {
  declare module.exports: $Exports<'rewire/testLib/debuggerModule'>;
}
declare module 'rewire/testLib/emptyModule.js' {
  declare module.exports: $Exports<'rewire/testLib/emptyModule'>;
}
declare module 'rewire/testLib/implicitGlobal.js' {
  declare module.exports: $Exports<'rewire/testLib/implicitGlobal'>;
}
declare module 'rewire/testLib/moduleA.js' {
  declare module.exports: $Exports<'rewire/testLib/moduleA'>;
}
declare module 'rewire/testLib/moduleB.js' {
  declare module.exports: $Exports<'rewire/testLib/moduleB'>;
}
declare module 'rewire/testLib/null.js' {
  declare module.exports: $Exports<'rewire/testLib/null'>;
}
declare module 'rewire/testLib/sealedObject.js' {
  declare module.exports: $Exports<'rewire/testLib/sealedObject'>;
}
declare module 'rewire/testLib/sharedTestCases.js' {
  declare module.exports: $Exports<'rewire/testLib/sharedTestCases'>;
}
declare module 'rewire/testLib/someOtherModule.js' {
  declare module.exports: $Exports<'rewire/testLib/someOtherModule'>;
}
declare module 'rewire/testLib/strictModule.js' {
  declare module.exports: $Exports<'rewire/testLib/strictModule'>;
}
declare module 'rewire/testLib/throwError.js' {
  declare module.exports: $Exports<'rewire/testLib/throwError'>;
}
