// flow-typed signature: fa3386e05ebfbd9b63b847d110aff969
// flow-typed version: <<STUB>>/saucelabs_v^1.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'saucelabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'saucelabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'saucelabs/lib/SauceLabs' {
  declare module.exports: any;
}

declare module 'saucelabs/lib/utils' {
  declare module.exports: any;
}

declare module 'saucelabs/test/bootstrap/index' {
  declare module.exports: any;
}

declare module 'saucelabs/test/helpers/index' {
  declare module.exports: any;
}

declare module 'saucelabs/test/SauceLabs' {
  declare module.exports: any;
}

declare module 'saucelabs/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'saucelabs/index' {
  declare module.exports: $Exports<'saucelabs'>;
}
declare module 'saucelabs/index.js' {
  declare module.exports: $Exports<'saucelabs'>;
}
declare module 'saucelabs/lib/SauceLabs.js' {
  declare module.exports: $Exports<'saucelabs/lib/SauceLabs'>;
}
declare module 'saucelabs/lib/utils.js' {
  declare module.exports: $Exports<'saucelabs/lib/utils'>;
}
declare module 'saucelabs/test/bootstrap/index.js' {
  declare module.exports: $Exports<'saucelabs/test/bootstrap/index'>;
}
declare module 'saucelabs/test/helpers/index.js' {
  declare module.exports: $Exports<'saucelabs/test/helpers/index'>;
}
declare module 'saucelabs/test/SauceLabs.js' {
  declare module.exports: $Exports<'saucelabs/test/SauceLabs'>;
}
declare module 'saucelabs/test/utils.js' {
  declare module.exports: $Exports<'saucelabs/test/utils'>;
}
