// flow-typed signature: 27fc103ef415f31714738d869c301e51
// flow-typed version: <<STUB>>/select2-bootstrap-theme_v0.1.0-beta.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'select2-bootstrap-theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'select2-bootstrap-theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'select2-bootstrap-theme/docs/js/anchor.min' {
  declare module.exports: any;
}

declare module 'select2-bootstrap-theme/docs/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'select2-bootstrap-theme/docs/js/respond.min' {
  declare module.exports: any;
}

declare module 'select2-bootstrap-theme/Gruntfile' {
  declare module.exports: any;
}

declare module 'select2-bootstrap-theme/tests/less_test' {
  declare module.exports: any;
}

declare module 'select2-bootstrap-theme/tests/scss_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'select2-bootstrap-theme/docs/js/anchor.min.js' {
  declare module.exports: $Exports<'select2-bootstrap-theme/docs/js/anchor.min'>;
}
declare module 'select2-bootstrap-theme/docs/js/bootstrap.min.js' {
  declare module.exports: $Exports<'select2-bootstrap-theme/docs/js/bootstrap.min'>;
}
declare module 'select2-bootstrap-theme/docs/js/respond.min.js' {
  declare module.exports: $Exports<'select2-bootstrap-theme/docs/js/respond.min'>;
}
declare module 'select2-bootstrap-theme/Gruntfile.js' {
  declare module.exports: $Exports<'select2-bootstrap-theme/Gruntfile'>;
}
declare module 'select2-bootstrap-theme/tests/less_test.js' {
  declare module.exports: $Exports<'select2-bootstrap-theme/tests/less_test'>;
}
declare module 'select2-bootstrap-theme/tests/scss_test.js' {
  declare module.exports: $Exports<'select2-bootstrap-theme/tests/scss_test'>;
}
