// flow-typed signature: 12b6fe6b4dd95571fda3fd9d50e4f717
// flow-typed version: <<STUB>>/select2_v^4.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'select2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'select2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'select2/dist/js/i18n/ar' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/az' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/bg' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/ca' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/cs' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/da' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/de' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/el' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/en' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/es' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/et' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/eu' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/fa' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/fi' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/fr' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/gl' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/he' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/hi' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/hr' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/hu' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/id' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/is' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/it' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/ja' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/km' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/ko' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/lt' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/lv' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/mk' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/ms' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/nb' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/nl' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/pl' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/pt-BR' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/pt' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/ro' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/ru' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/sk' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/sr-Cyrl' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/sr' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/sv' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/th' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/tr' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/uk' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/vi' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/zh-CN' {
  declare module.exports: any;
}

declare module 'select2/dist/js/i18n/zh-TW' {
  declare module.exports: any;
}

declare module 'select2/dist/js/select2.full' {
  declare module.exports: any;
}

declare module 'select2/dist/js/select2.full.min' {
  declare module.exports: any;
}

declare module 'select2/dist/js/select2' {
  declare module.exports: any;
}

declare module 'select2/dist/js/select2.min' {
  declare module.exports: any;
}

declare module 'select2/src/js/banner.end' {
  declare module.exports: any;
}

declare module 'select2/src/js/banner.start' {
  declare module.exports: any;
}

declare module 'select2/src/js/jquery.mousewheel.shim' {
  declare module.exports: any;
}

declare module 'select2/src/js/jquery.select2' {
  declare module.exports: any;
}

declare module 'select2/src/js/jquery.shim' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/compat/containerCss' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/compat/dropdownCss' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/compat/initSelection' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/compat/inputData' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/compat/matcher' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/compat/query' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/compat/utils' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/core' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/data/ajax' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/data/array' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/data/base' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/data/maximumInputLength' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/data/maximumSelectionLength' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/data/minimumInputLength' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/data/select' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/data/tags' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/data/tokenizer' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/defaults' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/diacritics' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/dropdown' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/dropdown/attachBody' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/dropdown/attachContainer' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/dropdown/closeOnSelect' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/dropdown/hidePlaceholder' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/dropdown/infiniteScroll' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/dropdown/minimumResultsForSearch' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/dropdown/search' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/dropdown/selectOnClose' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/dropdown/stopPropagation' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/ar' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/az' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/bg' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/ca' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/cs' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/da' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/de' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/el' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/en' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/es' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/et' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/eu' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/fa' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/fi' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/fr' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/gl' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/he' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/hi' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/hr' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/hu' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/id' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/is' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/it' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/ja' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/km' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/ko' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/lt' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/lv' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/mk' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/ms' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/nb' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/nl' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/pl' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/pt-BR' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/pt' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/ro' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/ru' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/sk' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/sr-Cyrl' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/sr' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/sv' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/th' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/tr' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/uk' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/vi' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/zh-CN' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/i18n/zh-TW' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/keys' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/options' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/results' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/selection/allowClear' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/selection/base' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/selection/clickMask' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/selection/eventRelay' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/selection/multiple' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/selection/placeholder' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/selection/search' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/selection/single' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/selection/stopPropagation' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/translation' {
  declare module.exports: any;
}

declare module 'select2/src/js/select2/utils' {
  declare module.exports: any;
}

declare module 'select2/src/js/wrapper.end' {
  declare module.exports: any;
}

declare module 'select2/src/js/wrapper.start' {
  declare module.exports: any;
}

// Filename aliases
declare module 'select2/dist/js/i18n/ar.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/ar'>;
}
declare module 'select2/dist/js/i18n/az.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/az'>;
}
declare module 'select2/dist/js/i18n/bg.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/bg'>;
}
declare module 'select2/dist/js/i18n/ca.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/ca'>;
}
declare module 'select2/dist/js/i18n/cs.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/cs'>;
}
declare module 'select2/dist/js/i18n/da.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/da'>;
}
declare module 'select2/dist/js/i18n/de.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/de'>;
}
declare module 'select2/dist/js/i18n/el.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/el'>;
}
declare module 'select2/dist/js/i18n/en.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/en'>;
}
declare module 'select2/dist/js/i18n/es.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/es'>;
}
declare module 'select2/dist/js/i18n/et.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/et'>;
}
declare module 'select2/dist/js/i18n/eu.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/eu'>;
}
declare module 'select2/dist/js/i18n/fa.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/fa'>;
}
declare module 'select2/dist/js/i18n/fi.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/fi'>;
}
declare module 'select2/dist/js/i18n/fr.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/fr'>;
}
declare module 'select2/dist/js/i18n/gl.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/gl'>;
}
declare module 'select2/dist/js/i18n/he.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/he'>;
}
declare module 'select2/dist/js/i18n/hi.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/hi'>;
}
declare module 'select2/dist/js/i18n/hr.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/hr'>;
}
declare module 'select2/dist/js/i18n/hu.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/hu'>;
}
declare module 'select2/dist/js/i18n/id.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/id'>;
}
declare module 'select2/dist/js/i18n/is.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/is'>;
}
declare module 'select2/dist/js/i18n/it.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/it'>;
}
declare module 'select2/dist/js/i18n/ja.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/ja'>;
}
declare module 'select2/dist/js/i18n/km.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/km'>;
}
declare module 'select2/dist/js/i18n/ko.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/ko'>;
}
declare module 'select2/dist/js/i18n/lt.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/lt'>;
}
declare module 'select2/dist/js/i18n/lv.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/lv'>;
}
declare module 'select2/dist/js/i18n/mk.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/mk'>;
}
declare module 'select2/dist/js/i18n/ms.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/ms'>;
}
declare module 'select2/dist/js/i18n/nb.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/nb'>;
}
declare module 'select2/dist/js/i18n/nl.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/nl'>;
}
declare module 'select2/dist/js/i18n/pl.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/pl'>;
}
declare module 'select2/dist/js/i18n/pt-BR.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/pt-BR'>;
}
declare module 'select2/dist/js/i18n/pt.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/pt'>;
}
declare module 'select2/dist/js/i18n/ro.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/ro'>;
}
declare module 'select2/dist/js/i18n/ru.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/ru'>;
}
declare module 'select2/dist/js/i18n/sk.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/sk'>;
}
declare module 'select2/dist/js/i18n/sr-Cyrl.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/sr-Cyrl'>;
}
declare module 'select2/dist/js/i18n/sr.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/sr'>;
}
declare module 'select2/dist/js/i18n/sv.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/sv'>;
}
declare module 'select2/dist/js/i18n/th.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/th'>;
}
declare module 'select2/dist/js/i18n/tr.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/tr'>;
}
declare module 'select2/dist/js/i18n/uk.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/uk'>;
}
declare module 'select2/dist/js/i18n/vi.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/vi'>;
}
declare module 'select2/dist/js/i18n/zh-CN.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/zh-CN'>;
}
declare module 'select2/dist/js/i18n/zh-TW.js' {
  declare module.exports: $Exports<'select2/dist/js/i18n/zh-TW'>;
}
declare module 'select2/dist/js/select2.full.js' {
  declare module.exports: $Exports<'select2/dist/js/select2.full'>;
}
declare module 'select2/dist/js/select2.full.min.js' {
  declare module.exports: $Exports<'select2/dist/js/select2.full.min'>;
}
declare module 'select2/dist/js/select2.js' {
  declare module.exports: $Exports<'select2/dist/js/select2'>;
}
declare module 'select2/dist/js/select2.min.js' {
  declare module.exports: $Exports<'select2/dist/js/select2.min'>;
}
declare module 'select2/src/js/banner.end.js' {
  declare module.exports: $Exports<'select2/src/js/banner.end'>;
}
declare module 'select2/src/js/banner.start.js' {
  declare module.exports: $Exports<'select2/src/js/banner.start'>;
}
declare module 'select2/src/js/jquery.mousewheel.shim.js' {
  declare module.exports: $Exports<'select2/src/js/jquery.mousewheel.shim'>;
}
declare module 'select2/src/js/jquery.select2.js' {
  declare module.exports: $Exports<'select2/src/js/jquery.select2'>;
}
declare module 'select2/src/js/jquery.shim.js' {
  declare module.exports: $Exports<'select2/src/js/jquery.shim'>;
}
declare module 'select2/src/js/select2/compat/containerCss.js' {
  declare module.exports: $Exports<'select2/src/js/select2/compat/containerCss'>;
}
declare module 'select2/src/js/select2/compat/dropdownCss.js' {
  declare module.exports: $Exports<'select2/src/js/select2/compat/dropdownCss'>;
}
declare module 'select2/src/js/select2/compat/initSelection.js' {
  declare module.exports: $Exports<'select2/src/js/select2/compat/initSelection'>;
}
declare module 'select2/src/js/select2/compat/inputData.js' {
  declare module.exports: $Exports<'select2/src/js/select2/compat/inputData'>;
}
declare module 'select2/src/js/select2/compat/matcher.js' {
  declare module.exports: $Exports<'select2/src/js/select2/compat/matcher'>;
}
declare module 'select2/src/js/select2/compat/query.js' {
  declare module.exports: $Exports<'select2/src/js/select2/compat/query'>;
}
declare module 'select2/src/js/select2/compat/utils.js' {
  declare module.exports: $Exports<'select2/src/js/select2/compat/utils'>;
}
declare module 'select2/src/js/select2/core.js' {
  declare module.exports: $Exports<'select2/src/js/select2/core'>;
}
declare module 'select2/src/js/select2/data/ajax.js' {
  declare module.exports: $Exports<'select2/src/js/select2/data/ajax'>;
}
declare module 'select2/src/js/select2/data/array.js' {
  declare module.exports: $Exports<'select2/src/js/select2/data/array'>;
}
declare module 'select2/src/js/select2/data/base.js' {
  declare module.exports: $Exports<'select2/src/js/select2/data/base'>;
}
declare module 'select2/src/js/select2/data/maximumInputLength.js' {
  declare module.exports: $Exports<'select2/src/js/select2/data/maximumInputLength'>;
}
declare module 'select2/src/js/select2/data/maximumSelectionLength.js' {
  declare module.exports: $Exports<'select2/src/js/select2/data/maximumSelectionLength'>;
}
declare module 'select2/src/js/select2/data/minimumInputLength.js' {
  declare module.exports: $Exports<'select2/src/js/select2/data/minimumInputLength'>;
}
declare module 'select2/src/js/select2/data/select.js' {
  declare module.exports: $Exports<'select2/src/js/select2/data/select'>;
}
declare module 'select2/src/js/select2/data/tags.js' {
  declare module.exports: $Exports<'select2/src/js/select2/data/tags'>;
}
declare module 'select2/src/js/select2/data/tokenizer.js' {
  declare module.exports: $Exports<'select2/src/js/select2/data/tokenizer'>;
}
declare module 'select2/src/js/select2/defaults.js' {
  declare module.exports: $Exports<'select2/src/js/select2/defaults'>;
}
declare module 'select2/src/js/select2/diacritics.js' {
  declare module.exports: $Exports<'select2/src/js/select2/diacritics'>;
}
declare module 'select2/src/js/select2/dropdown.js' {
  declare module.exports: $Exports<'select2/src/js/select2/dropdown'>;
}
declare module 'select2/src/js/select2/dropdown/attachBody.js' {
  declare module.exports: $Exports<'select2/src/js/select2/dropdown/attachBody'>;
}
declare module 'select2/src/js/select2/dropdown/attachContainer.js' {
  declare module.exports: $Exports<'select2/src/js/select2/dropdown/attachContainer'>;
}
declare module 'select2/src/js/select2/dropdown/closeOnSelect.js' {
  declare module.exports: $Exports<'select2/src/js/select2/dropdown/closeOnSelect'>;
}
declare module 'select2/src/js/select2/dropdown/hidePlaceholder.js' {
  declare module.exports: $Exports<'select2/src/js/select2/dropdown/hidePlaceholder'>;
}
declare module 'select2/src/js/select2/dropdown/infiniteScroll.js' {
  declare module.exports: $Exports<'select2/src/js/select2/dropdown/infiniteScroll'>;
}
declare module 'select2/src/js/select2/dropdown/minimumResultsForSearch.js' {
  declare module.exports: $Exports<'select2/src/js/select2/dropdown/minimumResultsForSearch'>;
}
declare module 'select2/src/js/select2/dropdown/search.js' {
  declare module.exports: $Exports<'select2/src/js/select2/dropdown/search'>;
}
declare module 'select2/src/js/select2/dropdown/selectOnClose.js' {
  declare module.exports: $Exports<'select2/src/js/select2/dropdown/selectOnClose'>;
}
declare module 'select2/src/js/select2/dropdown/stopPropagation.js' {
  declare module.exports: $Exports<'select2/src/js/select2/dropdown/stopPropagation'>;
}
declare module 'select2/src/js/select2/i18n/ar.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/ar'>;
}
declare module 'select2/src/js/select2/i18n/az.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/az'>;
}
declare module 'select2/src/js/select2/i18n/bg.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/bg'>;
}
declare module 'select2/src/js/select2/i18n/ca.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/ca'>;
}
declare module 'select2/src/js/select2/i18n/cs.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/cs'>;
}
declare module 'select2/src/js/select2/i18n/da.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/da'>;
}
declare module 'select2/src/js/select2/i18n/de.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/de'>;
}
declare module 'select2/src/js/select2/i18n/el.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/el'>;
}
declare module 'select2/src/js/select2/i18n/en.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/en'>;
}
declare module 'select2/src/js/select2/i18n/es.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/es'>;
}
declare module 'select2/src/js/select2/i18n/et.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/et'>;
}
declare module 'select2/src/js/select2/i18n/eu.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/eu'>;
}
declare module 'select2/src/js/select2/i18n/fa.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/fa'>;
}
declare module 'select2/src/js/select2/i18n/fi.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/fi'>;
}
declare module 'select2/src/js/select2/i18n/fr.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/fr'>;
}
declare module 'select2/src/js/select2/i18n/gl.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/gl'>;
}
declare module 'select2/src/js/select2/i18n/he.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/he'>;
}
declare module 'select2/src/js/select2/i18n/hi.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/hi'>;
}
declare module 'select2/src/js/select2/i18n/hr.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/hr'>;
}
declare module 'select2/src/js/select2/i18n/hu.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/hu'>;
}
declare module 'select2/src/js/select2/i18n/id.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/id'>;
}
declare module 'select2/src/js/select2/i18n/is.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/is'>;
}
declare module 'select2/src/js/select2/i18n/it.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/it'>;
}
declare module 'select2/src/js/select2/i18n/ja.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/ja'>;
}
declare module 'select2/src/js/select2/i18n/km.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/km'>;
}
declare module 'select2/src/js/select2/i18n/ko.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/ko'>;
}
declare module 'select2/src/js/select2/i18n/lt.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/lt'>;
}
declare module 'select2/src/js/select2/i18n/lv.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/lv'>;
}
declare module 'select2/src/js/select2/i18n/mk.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/mk'>;
}
declare module 'select2/src/js/select2/i18n/ms.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/ms'>;
}
declare module 'select2/src/js/select2/i18n/nb.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/nb'>;
}
declare module 'select2/src/js/select2/i18n/nl.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/nl'>;
}
declare module 'select2/src/js/select2/i18n/pl.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/pl'>;
}
declare module 'select2/src/js/select2/i18n/pt-BR.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/pt-BR'>;
}
declare module 'select2/src/js/select2/i18n/pt.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/pt'>;
}
declare module 'select2/src/js/select2/i18n/ro.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/ro'>;
}
declare module 'select2/src/js/select2/i18n/ru.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/ru'>;
}
declare module 'select2/src/js/select2/i18n/sk.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/sk'>;
}
declare module 'select2/src/js/select2/i18n/sr-Cyrl.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/sr-Cyrl'>;
}
declare module 'select2/src/js/select2/i18n/sr.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/sr'>;
}
declare module 'select2/src/js/select2/i18n/sv.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/sv'>;
}
declare module 'select2/src/js/select2/i18n/th.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/th'>;
}
declare module 'select2/src/js/select2/i18n/tr.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/tr'>;
}
declare module 'select2/src/js/select2/i18n/uk.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/uk'>;
}
declare module 'select2/src/js/select2/i18n/vi.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/vi'>;
}
declare module 'select2/src/js/select2/i18n/zh-CN.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/zh-CN'>;
}
declare module 'select2/src/js/select2/i18n/zh-TW.js' {
  declare module.exports: $Exports<'select2/src/js/select2/i18n/zh-TW'>;
}
declare module 'select2/src/js/select2/keys.js' {
  declare module.exports: $Exports<'select2/src/js/select2/keys'>;
}
declare module 'select2/src/js/select2/options.js' {
  declare module.exports: $Exports<'select2/src/js/select2/options'>;
}
declare module 'select2/src/js/select2/results.js' {
  declare module.exports: $Exports<'select2/src/js/select2/results'>;
}
declare module 'select2/src/js/select2/selection/allowClear.js' {
  declare module.exports: $Exports<'select2/src/js/select2/selection/allowClear'>;
}
declare module 'select2/src/js/select2/selection/base.js' {
  declare module.exports: $Exports<'select2/src/js/select2/selection/base'>;
}
declare module 'select2/src/js/select2/selection/clickMask.js' {
  declare module.exports: $Exports<'select2/src/js/select2/selection/clickMask'>;
}
declare module 'select2/src/js/select2/selection/eventRelay.js' {
  declare module.exports: $Exports<'select2/src/js/select2/selection/eventRelay'>;
}
declare module 'select2/src/js/select2/selection/multiple.js' {
  declare module.exports: $Exports<'select2/src/js/select2/selection/multiple'>;
}
declare module 'select2/src/js/select2/selection/placeholder.js' {
  declare module.exports: $Exports<'select2/src/js/select2/selection/placeholder'>;
}
declare module 'select2/src/js/select2/selection/search.js' {
  declare module.exports: $Exports<'select2/src/js/select2/selection/search'>;
}
declare module 'select2/src/js/select2/selection/single.js' {
  declare module.exports: $Exports<'select2/src/js/select2/selection/single'>;
}
declare module 'select2/src/js/select2/selection/stopPropagation.js' {
  declare module.exports: $Exports<'select2/src/js/select2/selection/stopPropagation'>;
}
declare module 'select2/src/js/select2/translation.js' {
  declare module.exports: $Exports<'select2/src/js/select2/translation'>;
}
declare module 'select2/src/js/select2/utils.js' {
  declare module.exports: $Exports<'select2/src/js/select2/utils'>;
}
declare module 'select2/src/js/wrapper.end.js' {
  declare module.exports: $Exports<'select2/src/js/wrapper.end'>;
}
declare module 'select2/src/js/wrapper.start.js' {
  declare module.exports: $Exports<'select2/src/js/wrapper.start'>;
}
